config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'venues#index'
  resources :venues, except: %i[edit update] do
    member do
      get  :test_solution
      post :test_solution
      post :update_seat
      post :free_sample_seat_group
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/seat.rb
# frozen_string_literal: true

class Seat < ApplicationRecord
  belongs_to :venue
  validates :row, presence: true, numericality: { greater_than: 0 }
  validates :column, presence: true, numericality: { greater_than: 0 }
  validates :available, inclusion: { in: [true, false] } # disallow nil

  LETTERS = %w[A B C D E F G H I J K L M N O P Q R S T U V W X Y Z].freeze

  AVAILABLE_STATUS = 'AVAILABLE'
  UNAVAILABLE_STATUS = 'NOT AVAILABLE'

  default_scope { order :row, :column }

  scope :available, -> { where available: true }
  scope :unavailable, -> { where.not available: true }

  def name
    "#{row_letter}#{column}"
  end

  def row_letter
    count, index = (row - 1 + LETTERS.count).divmod LETTERS.count
    LETTERS[index] * count
  end

  def status
    if available?
      AVAILABLE_STATUS
    else UNAVAILABLE_STATUS
    end
  end
end

app/models/venue.rb
# frozen_string_literal: true

class Venue < ApplicationRecord
  has_many :seats, dependent: :delete_all
  validates :rows, presence: true, numericality: { greater_than: 0 }
  validates :columns, presence: true, numericality: { greater_than: 0 }
  after_create :populate_seats!

  def free_sample_seat_group(size:)
    row = rand(rows) + 1
    start_column = rand(columns - size) + 1
    end_column = start_column + size
    seats.where(row: row, column: start_column...end_column).update_all available: true # rubocop:disable Rails/SkipsModelValidations
  end

  # output is 0-indexed, inputs are 1-indexed
  def seat_index(row, column)
    (row - 1) * columns + (column - 1)
  end

  private

  def populate_seats!
    seat_attributes = []
    1.upto(rows).each do |row|
      1.upto(columns).each do |column|
        seat_attributes << { venue_id: id, row: row, column: column, available: false }
      end
    end
    Seat.insert_all! seat_attributes # rubocop:disable Rails/SkipsModelValidations
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/venues_controller.rb
# frozen_string_literal: true

class VenuesController < ApplicationController
  before_action :set_venue, only: %i[
    show destroy update_seat
    test_solution free_sample_seat_group
  ]

  # GET /venues or /venues.json
  def index
    @venues = Venue.includes(:seats).all
  end

  # GET /venues/1 or /venues/1.json
  def show; end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # POST /venues or /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1 or /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_seat
    seat_params = params.require(:seat).permit(:id, :available)
    @seat = @venue.seats.find(seat_params[:id])
    if @seat&.update(available: seat_params[:available])
      redirect_to @venue, notice: 'Seat updated.'
    else redirect_to @venue, notice: 'Seat update failed.'
    end
  end

  def free_sample_seat_group
    free_params = params.require(:venue).permit(:group_size, :count)
    group_size = free_params.fetch(:group_size).to_i
    count = [free_params.fetch(:count).to_i, 100].min
    count.times do
      @venue.free_sample_seat_group size: group_size
    end
    redirect_to @venue, notice: 'Sample seat group(s) freed.'
  end

  def test_solution
    if request.post?
      solver = MovieSeatsSolver.new
      solver.input_data = JSON.parse(solution_params[:input_data])
      solver.parse_input_data!
      solver.requested_group_size = solution_params[:requested_group_size].to_i
      solver.solve!
      render json: solver.solution_json_data, status: :ok
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_venue
    @venue = Venue.includes(:seats).find(params[:id])
  end

  def solution_params
    params.require(:venue).permit(:input_data, :requested_group_size)
  end

  def venue_params
    params.require(:venue).permit(:rows, :columns)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/movie_seats_solver.rb
# frozen_string_literal: true

class MovieSeatsSolver
  AVAILABLE_STATUS = 'AVAILABLE'
  ROW_LETTERS = %w[a b c d e f g h i j k l m n o p q r s t u v w x y z].freeze

  attr_accessor :input_data, :requested_group_size, :venue, :seat_groups, :best_group

  def parse_venue(venue_data)
    venue = Venue.new
    layout = venue_data.fetch('layout')
    venue.rows = layout.fetch('rows')
    venue.columns = layout.fetch('columns')
    venue
  end

  def parse_seat(seat_data)
    seat = Seat.new
    seat.row = row_number seat_data.fetch('row')
    seat.column = seat_data.fetch 'column'
    seat.id = seat_data.fetch 'id'
    seat
  end

  def group_seats(seats)
    groups = []
    seats.each do |seat|
      if seat.next_to? groups.last&.last
        groups.last << seat
      else groups << [seat]
      end
    end
    groups
  end

  def sort_seats(seats)
    seats.sort_by do |seat|
      venue.seat_index seat
    end
  end

  def parse_input_data!
    self.venue = parse_venue(input_data.fetch('venue'))

    seats = []
    input_data.fetch('seats').each_value do |seat_data|
      next unless seat_data.fetch('status') == AVAILABLE_STATUS

      seats << parse_seat(seat_data)
    end
    self.seat_groups = group_seats(sort_seats(seats))
  end

  def solution_json_data
    return {} unless best_group

    input_data['seats'].slice(*best_group.map(&:id))
  end

  def requested_size_subgroups(group)
    return [group] if group.size == requested_group_size

    subgroup_count = group.size - requested_group_size
    (0...subgroup_count).map do |subgroup_starting_index|
      group.slice(subgroup_starting_index, requested_group_size)
    end
  end

  def size_seat_groups!
    requested_size_groups = []
    seat_groups.each do |group|
      unless group.size < requested_group_size
        requested_size_groups += requested_size_subgroups(group)
      end
    end
    self.seat_groups = requested_size_groups
  end

  def solve!
    size_seat_groups!
    self.best_group = seat_groups.min_by do |group|
      group_row = group.first.row
      group_average_column = Rational(group.sum(&:column), group.size) # avoid floating point issues
      venue.distance_to_front_and_center_from group_row, group_average_column
    end || []
  end

  def row_number(row_code)
    letter = row_code.first
    base_index = ROW_LETTERS.index(letter) + 1
    extra_length = row_code.length - 1
    extra_length * 26 + base_index
  end

  class Venue
    attr_accessor :rows, :columns

    def center_column_number
      Rational(columns + 1, 2) # e.g. 10 columns -> center column number is (11/2) = 5.5
    end

    def distance_to_front_and_center_from(row, column)
      forward_distance = row - 1 # front row is always 1
      side_distance = column - center_column_number
      Math.sqrt(forward_distance.abs2 + side_distance.abs2) # Thanks, Pythagoras
    end

    def seat_index(seat)
      columns * seat.row + seat.column
    end
  end

  class Seat
    attr_accessor :row, :column, :id

    def next_to?(other_seat)
      return false unless other_seat.is_a? Seat
      return false unless other_seat.row == row
      return false unless (other_seat.column - column).abs == 1

      return true
    end
  end
end

app/helpers/venues_helper.rb
# frozen_string_literal: true

module VenuesHelper
  def solution_input_json(venue)
    data = {}
    data[:venue] = {}
    data[:venue][:layout] = { rows: venue.rows, columns: venue.columns }
    data[:seats] = {}
    venue.seats.each do |seat|
      data[:seats][seat.name] =
        { id: seat.name, row: seat.row_letter.downcase, column: seat.column, status: seat.status }
    end
    data.to_json
  end

  def percentage_available_seats(venue)
    percentage = 100 * venue.seats.available.count / venue.seats.count.to_f
    '%.2f%%' % percentage
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Movieseats
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/venues/_form.html.haml
= form_with(model: venue) do |form|
  - if venue.errors.any?
    #error_explanation
      %h2
        = pluralize(venue.errors.count, "error")
        prohibited this venue from being saved:
      %ul
        - venue.errors.each do |error|
          %li= error.full_message
  .field
    = form.label :rows
    = form.number_field :rows
  .field
    = form.label :columns
    = form.number_field :columns
  .actions
    = form.submit

app/views/venues/index.html.haml
%p#notice= notice
%h1 Venues
- if @venues.present?
  %table
    %thead
      %tr
        %th Rows
        %th Columns
        %th Available seats
        %th Total seats
        %th % available seats
        %th{colspan: 2}
    %tbody
      - @venues.each do |venue|
        %tr
          %td= venue.rows
          %td= venue.columns
          %td= venue.seats.count
          %td= venue.seats.available.count
          %td= percentage_available_seats(venue)
          %td= link_to 'Show', venue
          %td= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Venue', new_venue_path

app/views/venues/new.html.haml
%h1 New Venue
= render 'form', venue: @venue
= link_to 'Back', venues_path

app/views/venues/show.html.haml
- if notice
  %p#notice= notice
%p
  %strong Rows:
  = @venue.rows
%p
  %strong Columns:
  = @venue.columns
%table.seats
  - 1.upto(@venue.rows).each do |row|
    %tr
      - 1.upto(@venue.columns).each do |column|
        %td
          - seat = @venue.seats[@venue.seat_index row, column]
          = seat.name
          = form_with scope: seat, url: update_seat_venue_path(@venue) do |form|
            = form.hidden_field :id, value: seat.id
            = form.check_box :available, value: seat.available?, onchange: 'this.form.submit();'
= form_with scope: @venue, url: free_sample_seat_group_venue_path(@venue), method: :post do |form|
  = form.label :group_size, 'Free sample groups of size:'
  = form.number_field :group_size, value: 1, min: 1, max: @venue.columns
  = form.label :count, 'Number of groups:'
  = form.number_field :count, value: 1, min: 1, max: 100
  = form.submit 'Free group'
.solution_test= link_to 'Test Solution', test_solution_venue_path(@venue)
= link_to 'Back', venues_path

app/views/venues/test_solution.haml
%h1 Test Solution

= form_with model: @venue, url: test_solution_venue_path(@venue), method: :post, class: 'solution_form', local: false do |form|
	= form.label :input_data, 'Solution input JSON:'
	= form.text_area :input_data, value: solution_input_json(@venue), cols: 250, rows: 30, readonly: true
	= form.label :requested_group_size, 'Requested group size:'
	= form.number_field :requested_group_size, value: 1, min: 1, max: @venue.columns
	= form.submit 'Test solution'
= label_tag :solution, 'Solution:'
= text_area_tag :solution, nil, cols: 250, rows: 10, disabled: true, class: 'solution_field'

.actions
	= link_to 'Back', venue_path(@venue)